import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tutorialSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Lab Setup',
      link: {
        type: 'doc',
        id: 'lab-setup/overview',
      },
      items: [
        'lab-setup/digital-twin-workstation',
        'lab-setup/cloud-ether-lab',
        'lab-setup/economy-jetson-kit',
      ],
    },
    {
      type: 'category',
      label: 'Module 1: The Robotic Nervous System',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-1-robotic-nervous-system',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 2: The Digital Twin',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-2-digital-twin',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 3: The AI-Robot Brain',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-3-ai-robot-brain',
        },
      ],
    },
    {
      type: 'category',
      label: 'Module 4: Vision-Language-Action',
      items: [
        {
          type: 'autogenerated',
          dirName: 'module-4-vision-language-action',
        },
      ],
    },
    {
      type: 'category',
      label: 'Capstone Project',
      items: [
        {
          type: 'autogenerated',
          dirName: 'capstone-project',
        },
      ],
    },
  ],
};

export default sidebars;
